version: '3'

networks:
  default:
      name: podman
services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:18
    command: sh -c 'npx create-react-app ./ && npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    networks:
      - default